version: '2'

services:

  client:
    image: "node:16"
    user: "node"
    working_dir: /usr/src/app      
    volumes:
      - .:/usr/src/app
    environment:
      FAST_REFRESH: "true"
      WDS_SOCKET_PORT: 3002
      REACT_APP_REALM_APP_ID: "realm-tinkering-uvkwf"
      REACT_APP_REALM_DASHBOARD_URL: "https://charts.mongodb.com/charts-testing-grounds-nddfk"
      REACT_APP_REALM_DASHBOARD_ID: "c8fb9593-3d7d-4e4e-8613-a344968ffc1a"

    ports:
      - "3001:3000"
      - "3002:3000"
    expose:
      - "3001"
    command: "npm start"